### ISSUE TITLE
INFILE AND MASKFILE missing

### ISSUE THREAD

**Issue by amir-abdi** [Mr-Grieves/RL-Ultra3D#1]
@Mr-Grieves 
gym_ultra3d/envs/ultra3d_env.py:16

INFILE = '/home/nathanvw/dev/RL/data/3DUS/np/np06resized.npy'
MASKFILE = '/home/nathanvw/dev/RL/data/3DUS/np/mask.png'

**Comment by Mr-Grieves** [comment]
Added the missing files to repo. Also changed the absolute paths to relative ones
